services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/jwt_demo
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules  # Préserve le répertoire node_modules du conteneur

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: